### ISSUE TITLE
eyes.checkWindow() fails when run locally

### ISSUE THREAD

**Issue by hepiyellow** [wix/eyes.it#11]
Eyes doesn't create snapshots locally, since we don't have API key set locally.
But it is important to be able to debug e2e eyes tests locally, before creating a PR.

Failing with this message:
```
Failed: Promise factory was not initialized with proper callback
  Stack:
    Error: Promise factory was not initialized with proper callback
        at PromiseFactory.makePromise (/Users/erezm/Projects/wix-style-react/node_modules/eyes.utils/src/PromiseFactory.js:49:15)
        at Eyes.check (/Users/erezm/Projects/wix-style-react/node_modules/eyes.selenium/src/Eyes.js:235:44)
        at Eyes.checkWindow (/Users/erezm/Projects/wix-style-react/node_modules/eyes.selenium/src/Eyes.js:528:21)
```

**Comment by hepiyellow** [comment]
It seems that there are tests which is it:
https://github.com/wix-private/ecom/blob/1349724c7c907c956de084edc6bf2e75c4f69602/client/wixstores-client/wixstores-client-checkout/test/e2e/app.e2e.ts

I need to verify if this test works when run locally. If so, then how?

**Comment by roymiloh** [comment]
I'd advise to ask @AdirAmsalem, as he wrote that code.

**Comment by hepiyellow** [comment]
I already did. He said they didn’t make any special configuration. He recalls the tests were run locally, but doesn’t know if they do now.
I’ll have to check the project out and try it myself.

**Comment by roymiloh** [comment]
Thanks @hepiyellow!

**Comment by hepiyellow** [comment]
I run `wixstores-client-checkout`'s e2e tests locally and they fail for the same reason.

**Comment by hepiyellow** [comment]
@roymiloh , @liorur wrote me: "e2e often does not pass locally, not sure why"

**Comment by roymiloh** [comment]
Done https://github.com/wix/eyes.it/commit/470904d573d698e23f872f0cfff8226928548bcc.
